### ISSUE TITLE
Is it valid ESC in eisu+kana key

### ISSUE THREAD

**Issue by bsnresearcher** [s-show/KE-complex_modifications#1]
Dear author. 

Thank you very much to have made enthumble mode.

One problem:

In "(enthumble) 無変換/英数+「Space/かな」で「Return/Escape」" , ESC is invalid in pushed eisu key + kana key.

Would you help me to solve this problem.

MyEnv:
- OS: 10.12.6
- Karabiner-Element: 11.5.0
-  "(enthumble) 無変換/英数+「Space/かな」で「Return/Escape」"  is set to first rule.

**Comment by s-show** [comment]
今まで回答できなくて申し訳ありません。
いただいたISSUEに気がつかず、放置してしまいました。
バグを直しましたので、よろしければ再度使用してみてください。
今後はこのようなことがないよう注意します。

---In English---
I am sorry I can not answer until now.
I did not notice the ISSUE that I received, and I left it.
I fixed the bug, so please use it again if you do not mind.
I will be careful not to have this kind of thing in the future.

**Comment by bsnresearcher** [comment]
ありがとうございました．
(ちょっと急ぎでしたので，その時に改造して今も使わせて頂いております）
